ZDOTDIR="$HOME/.config/zsh"

QT_QPA_PLATFORMTHEME=gtk2
MOZ_ENABLE_WAYLAND=1
GTK_IM_MODULE=fcitx5
QT_IM_MODULE=fcitx5
XMODIFIERS=@im=fcitx5
SDL_VIDEODRIVER=wayland
_JAVA_AWT_WM_NONREPARENTING=1
QT_QPA_PLATFORM=wayland
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
XDG_CURRENT_DESKTOP=sway
XDG_SESSION_DESKTOP=sway
# vim:ft=zsh:nowrap
