## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
# set you color palette

palette = "catppuccin_mocha"

add_newline = true
format='''[\[$user($hostname)\]](white) $directory ([\[$git_branch(:$git_commit)(:$git_status)(:$git_state)\]](yellow))$line_break$character'''
right_format = '''($jobs)($status)($cmd_duration)$time'''

[os]
disabled = false
style = "blue"
# format = '[$symbol(v$version)(  $edition)(  $codename)(  $type)]($style)'
## uncomment the format above for all available information and comment out the line below
format = '[$symbol]($style)'
## other variables:
##   name = The current operating system name
##   type = The current operating system type
##   codename = The current operating system codename, if applicable
##   edition = The current operating system edition, if applicable
##   version = The current operating system version, if applicable

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " " 
CentOS = " " 
Debian = " "
DragonFly = " " 
Emscripten = " " 
EndeavourOS = " " 
Fedora = " " 
FreeBSD = " " 
Garuda = "󰛓 " 
Gentoo = " " 
HardenedBSD = "󰔇  " 
Illumos = " " 
Linux = " " 
Mabox = "󰆦  " 
Macos = " " 
Manjaro = " " 
Mariner = " " 
MidnightBSD = " "
Mint = "󰣭  "
NetBSD = " "
NixOS = " "
OpenBSD = " "
OpenCloudOS = " " 
openEuler = "󰏒  " 
openSUSE = " " 
OracleLinux = "󰌷  " 
Pop = " " 
Raspbian = " " 
Redhat = "󱄛 " 
RedHatEnterprise = " "
Redox = "󰀘  "
Solus = " " 
SUSE = " " 
Ubuntu = " "
Unknown = " " 
Windows = " "

[username]
format = '[$user](blue)'
show_always = true

[hostname]
format = '[@$hostname](teal)'

[character]
success_symbol = "[](green)"
error_symbol = "[](red)"
vimcmd_symbol = "[  ](bg:blue fg:mantle)[](fg:blue)"
vimcmd_visual_symbol = "[  ](bg:mauve fg:mantle)[](fg:mauve)"
vimcmd_replace_symbol = "[  ](bg:peach fg:mantle)[](fg:peach)"
format = "$symbol "

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = 'green'
truncation_length = 6
truncation_symbol = '.../'
truncate_to_repo = false
use_os_path_sep = false
use_logical_path = true

[git_branch]
format = "[$branch](yellow)"

[git_commit]
format = '[$hash](yellow)'

[git_status]
format = '[$all_status$ahead_behind](yellow)'

[git_state]
format = '[$state($progress_current/$progress_total)](yellow)'

[line_break]
disabled = false

[time]
format = '[\[$time\]](green)'
disabled = false

[cmd_duration]
format = '[\[$duration\]](yellow)'
min_time = 1
show_milliseconds = true
disabled = false

[status]
format = '[\[$status(:$common_meaning)(:$signal_name)\]](red)'
disabled = false

[jobs]
format = '[\[$symbol(:$number)\]](teal)'
symbol = '⚙'
symbol_threshold = 1
number_threshold = 2

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

