# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.
# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = ""
"termite" = ""
"terminal" = ""
"kitty" = ""
"github" = ""
"rust" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"chrome" = ""
"file manager" = ""
"nautilus" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"nvim" = ""
"gthumb" = ""
"eog" = ""
"menu" = ""
"calculator" = ""
"transmission" = ""
"videostream" = ""
"mpv" = ""
"vlc" = ""
"mplayer" = ""
"music" = ""
"disk usage" = ""
".pdf" = ""
"spotify" = ""
"gnome" = ""
"discord" = "\u200eﭮ"
"bitwarden" = ""
"steam" = ""
"snapper" = ""
"helvum" = ""
"pavucontrol" = ""
"code" = "﬏"
"obs" = ""
"xournal++" = "ﴬ"
"wezterm" = ""

[other]
fallback_icon = "∅"
deduplicate_icons = false
separator = ": "
