#!/bin/bash

CRE=$(tput setaf 1)
CYE=$(tput setaf 3)
CGR=$(tput setaf 2)
CBL=$(tput setaf 4)
BLD=$(tput bold)
CNC=$(tput sgr0)

crepos=/mnt/c/repos
wslconf=wsl.conf
pacconf=pacman.conf

clear
logo () {

	local text="${1:?}"
	echo -en "
    ██████████ ██████   █████ █████ █████   ████ ██████████
   ░███░░░░░░█░░██████ ░░███ ░░███ ░░███   ███░ ░███░░░░███
   ░███     ░  ░███░███ ░███  ░███  ░███  ███   ░░░    ███
   ░█████████  ░███░░███░███  ░███  ░███████          ███
   ░░░░░░░░███ ░███ ░░██████  ░███  ░███░░███        ███
    ███   ░███ ░███  ░░█████  ░███  ░███ ░░███      ███
   ░░████████  █████  ░░█████ █████ █████ ░░████   ███
    ░░░░░░░░  ░░░░░    ░░░░░ ░░░░░ ░░░░░   ░░░░   ░░░\n\n"
    printf ' %s [%s%s %s%s %s]%s\n\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}"
}

########## ---------- You must not run this as root ---------- ##########
logo "Arch WSL Init."
read -n1 -rep "\nReady? (y,n)" CFG
if [[ $CFG =~ ^[Yy]$ ]]; then
  sudo cat $crepos/$wslconf > /etc/$wslconf
  sudo cat $crepos/$pacconf > /etc/$pacconf
fi
sleep 2
clear

logo "WSL Config"
  cat $crepos/$wslconf > /etc/$wslconf
  cat $crepos/$pacconf > /etc/$pacconf
sleep 2
clear

logo "Key fix."
sudo pacman-key -d A2861ABFD897DD37

#download the new key
wget https://pkg.wslutiliti.es/public.key
sudo pacman-key --add public.key

#locally sign the new key
sudo pacman-key --lsign-key 2D4C887EB08424F157151C493DD50AA7E055D853
sleep 2
clear

logo "Full system update."
sudo pacman -Syu --noconfirm
sleep 2
printf "%s%sInit complete.%s\n" "${BLD}" "${CGR}" "${CNC}"