#!/bin/bash

main() {
  BuildNeovim
}

src=https://github.com/neovim/neovim
dst=$HOME/source/neovim

BuildNeovim() {
  if [[ -d ${dst} ]]; then
    echo 'Updating neovim source.'
    cd ${dst}
    git pull
  else
    mkdir $HOME/source
    echo 'Cloning neovim source.'
    git clone $src $dst && cd $dst
    echo 'Building neovim.'
    sudo make CMANE_BUILD=RelWithDebInfo install
    cd $HOME
  fi
}

main "$@"
