lastupdatecheck: 0
recentrepos:
- /home/snikt/dotfiles
- /home/snikt/dev/neoviim
- /mnt/c/repos/dotfiles
startuppopupversion: 5
customcommandshistory:
- state
- nvim zsh
- q
hidecommandlog: false
ignorewhitespaceindiffview: false
