lastupdatecheck: 0
recentrepos:
- /home/snikt/dotfiles
- /home/snikt/repos/dots
- /home/snikt/repos/dots/archdots
- /mnt/c/repos/dotfiles
startuppopupversion: 5
customcommandshistory:
- nvim zsh
- state
hidecommandlog: false
ignorewhitespaceindiffview: false
