github.com:
    users:
        5nik7:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: 5nik7
