github.com:
    users:
        5nik7:
            oauth_token: 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
    git_protocol: https
    user: 5nik7
    oauth_token: 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
