github.com:
    users:
        5nik7:
            oauth_token: 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
    git_protocol: https
    user: 5nik7
    oauth_token: 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
