#!/bin/bash

CRE=$(tput setaf 1)
CYE=$(tput setaf 3)
CGR=$(tput setaf 2)
CBL=$(tput setaf 4)
BLD=$(tput bold)
CNC=$(tput sgr0)

dotdir=~/dotfiles

clear
logo() {

	local text="${1:?}"
	echo -en "\n
    ██████████      ███████    ██████████ ██████████
   ░░███░░░░███   ███░░░░░███ ░███░░░░███░███░░░░░░█
    ░███   ░░███ ███     ░░███░░░    ███ ░███     ░
    ░███    ░███░███      ░███      ███  ░█████████
    ░███    ░███░███      ░███     ███   ░░░░░░░░███
    ░███    ███ ░░███     ███     ███     ███   ░███
    ██████████   ░░░███████░     ███     ░░████████
   ░░░░░░░░░░      ░░░░░░░      ░░░       ░░░░░░░░\n\n"
	printf ' %s [%s%s %s%s %s]%s\n\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}"
}

########## ---------- You must not run this as root ---------- ##########
logo "I'm going to break it... "

while true; do
	read -n1 -rep "Would you like to break everything? (y,n)" yn
	case $yn in
	[Yy]*) break ;;
	[Nn]*) exit ;;
	*) printf " Error: just write 'y' or 'n'\n\n" ;;
	esac
done

sudo pacman -Syyuu --noconfirm

dependencias=(git base-devel base-devel cmake unzip ninja curl unrar jq pacman-contrib rustup nodejs npm luarocks go python-pip \
	xdg-user-dirs hyprland sway waybar sddm-git wlogout wl-clipboard \
	ffmpeg viewnior kitty alacritty foot dunst rofi exa ranger starship lsd \
	polkit-gnome nwg-look-bin qt5ct htop btop ffmpegthumbs papirus-icon-theme catppuccin-gtk-theme-mocha \
	zsh exa ripgrep lazygit fd thunar vim bat neofetch cmatrix imagemagick pywal firefox \
	ttf-nerd-fonts-symbols-common otf-firamono-nerd inter-font otf-sora ttf-fantasque-nerd noto-fonts noto-fonts-emoji ttf-comfortaa \
  ttf-jetbrains-mono ttf-jetbrains-mono-nerd ttf-terminus-nerd ttf-inconsolata ttf-joypixels)

is_installed() {
	pacman -Qi "$1" &>/dev/null
	return $?
}

printf "%s%sChecking for required packages...%s\n" "${BLD}" "${CBL}" "${CNC}"
for pkgs in "${dependencias[@]}"; do
	if ! is_installed "$pkgs"; then
		paru -S "$pkgs" --noconfirm
		printf "\n"
	else
		printf '%s%s is already installed on your system!%s\n' "${CGR}" "$pkgs" "${CNC}"
	fi
done

dotdir=~/dotfiles
confdir=~/.config

	echo "Deleting symlinks."
	rm -rfv "$HOME/.config/alacritty"
	rm -rfv "$HOME/.config/bat"
	rm -rfv "$HOME/.config/btop"
	rm -rfv "$HOME/.config/dunst"
	rm -rfv "$HOME/.config/htop"
	rm -rfv "$HOME/.config/hypr"
	rm -rfv "$HOME/.config/kitty"
	rm -rfv "$HOME/.config/lazygit"
	rm -rfv "$HOME/.config/nvim"
	rm -rfv "$HOME/.config/paru"
	rm -rfv "$HOME/.config/ranger"
	rm -rfv "$HOME/.config/rofi"
	rm -rfv "$HOME/.config/starship"
	rm -rfv "$HOME/.config/sway"
	rm -rfv "$HOME/.config/swaylock"
	rm -rfv "$HOME/.config/waybar"
	rm -rfv "$HOME/.config/wlogout"
	rm -rfv "$HOME/.config/zsh"
	rm -rfv "$HOME/.gitconfig"
	rm -rfv "$HOME/.nanorc"
	rm -rfv "$HOME/.scripts"
	rm -rfv "$HOME/.vimrc"
	rm -rfv "$HOME/.wallpapers"
	rm -rfv "$HOME/.zprofile"
	rm -rfv "$HOME/.zshenv"
	rm -rfv "$HOME/.zshrc"

  echo "Creating symlinks."
	ln -fsv "$dotdir/config/alacritty" "$HOME/.config/"
	ln -fsv "$dotdir/config/bat" "$HOME/.config/"
	ln -fsv "$dotdir/config/dunst" "$HOME/.config/"
	ln -fsv "$dotdir/config/htop" "$HOME/.config/"
	ln -fsv "$dotdir/config/kitty" "$HOME/.config/"
	ln -fsv "$dotdir/config/hypr" "$HOME/.config/"
	ln -fsv "$dotdir/config/lazygit" "$HOME/.config/"
	ln -fsv "$dotdir/config/nvim" "$HOME/.config/"
	ln -fsv "$dotdir/config/paru" "$HOME/.config/"
	ln -fsv "$dotdir/config/ranger" "$HOME/.config/"
	ln -fsv "$dotdir/config/rofi" "$HOME/.config/rofi"
	ln -fsv "$dotdir/config/starship" "$HOME/.config/starship"
	ln -fsv "$dotdir/config/sway" "$HOME/.config/sway"
	ln -fsv "$dotdir/config/swaylock" "$HOME/.config/swaylock"
	ln -fsv "$dotdir/config/waybar" "$HOME/.config/waybar"
	ln -fsv "$dotdir/config/wlogout" "$HOME/.config/wlogout"
	ln -fsv "$dotdir/config/zsh" "$HOME/.config/zsh"
	ln -fsv "$dotdir/home/.gitconfig" "$HOME/.gitconfig"
	ln -fsv "$dotdir/home/.nanorc" "$HOME/.nanorc"
	ln -fsv "$dotdir/home/.vimrc" "$HOME/.vimrc"
	ln -fsv "$dotdir/home/.zshenv" "$HOME/.zshenv"
	ln -fsv "$dotdir/.scripts" "$HOME/.scripts"
	ln -fsv "$dotdir/.wallpapers" "$HOME/.wallpapers"

	chmod +x ~/dotfiles/scripts/do75
	chmod +x ~/dotfiles/config/hypr/xdg-portal-hyprland
	chmod +x ~/dotfiles/config/waybar/scripts/waybar-wttr.py
	chmod +x ~/dotfiles/config/ranger/scope.sh
fi
